# Generated by Django 4.1.1 on 2023-01-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200, null=True)),
                ('procedure', models.TextField(null=True)),
                ('nie', models.CharField(max_length=200, null=True)),
                ('dni', models.CharField(max_length=200, null=True)),
                ('passport', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('birth_year', models.CharField(max_length=200, null=True)),
                ('origin_country', models.CharField(max_length=200, null=True)),
                ('expiration_date', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('appointment_approved', models.BooleanField(default=False, null=True)),
                ('reason', models.TextField(null=True)),
            ],
        ),
    ]
