# Generated by Django 3.2.7 on 2023-01-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_model',
            name='free',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
