# Generated by Django 3.2.7 on 2023-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_bot', '0002_data_model_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_model',
            name='free',
        ),
        migrations.AddField(
            model_name='data_model',
            name='appointment',
            field=models.CharField(default='NotApproved', max_length=200, null=True),
        ),
    ]
